
[env]
TERM = "screen-256color"

[window]
opacity = 0.80
blur = true
decorations = "None"
padding = { x = 8, y = 0 }

[font]
normal = { family = "Commit Mono Nerd Font", style = "Bold" }

[general]
import = ["~/Repositories/dotfiles/config/alacritty/tokyonight_moon.toml"]

[terminal]
shell = "/bin/fish"
