add_newline = true

# Tokyo Night - Storm,
# bg_dark = "#1f2335",
# bg = "#24283b",
# bg_highlight = "#292e42",
# terminal_black = "#414868",
# fg = "#c0caf5",
# fg_dark = "#a9b1d6",
# fg_gutter = "#3b4261",
# dark3 = "#545c7e",
# comment = "#565f89",
# dark5 = "#737aa2",
# blue0 = "#3d59a1",
# blue = "#7aa2f7",
# cyan = "#7dcfff",
# blue1 = "#2ac3de",
# blue2 = "#0db9d7",
# blue5 = "#89ddff",
# blue6 = "#b4f9f8",
# blue7 = "#394b70",
# magenta = "#bb9af7",
# magenta2 = "#ff007c",
# purple = "#9d7cd8",
# orange = "#ff9e64",
# yellow = "#e0af68",
# green = "#9ece6a",
# green1 = "#73daca",
# green2 = "#41a6b5",
# teal = "#1abc9c",
# red = "#f7768e",
# red1 = "#db4b4b",
# git = { change = "#6183bb", add = "#449dab", delete = "#914c54" },
# gitSigns = {
#   add = "#266d6a",
#   change = "#536c9e",
#   delete = "#b2555b",
# },

# Tokyo Night - Moon
# bg_dark = "#1e2030",
# bg = "#222436",
# bg_highlight = "#2f334d",
# terminal_black = "#444a73",
# fg = "#c8d3f5",
# fg_dark = "#828bb8",
# fg_gutter = "#3b4261",
# dark3 = "#545c7e",
# comment = "#7a88cf",
# dark5 = "#737aa2",
# blue0 = "#3e68d7",
# blue = "#82aaff",
# cyan = "#86e1fc",
# blue1 = "#65bcff",
# blue2 = "#0db9d7",
# blue5 = "#89ddff",
# blue6 = "#b4f9f8",
# blue7 = "#394b70",
# purple = "#fca7ea",
# magenta2 = "#ff007c",
# magenta = "#c099ff",
# orange = "#ff966c",
# yellow = "#ffc777",
# green = "#c3e88d",
# green1 = "#4fd6be",
# green2 = "#41a6b5",
# teal = "#4fd6be",
# red = "#ff757f",
# red1 = "#c53b53",

format = """
[](fg:#41a6b5)\
$hostname\
$username\
[](fg:#41a6b5 bg:#3e68d7 )\
$directory\
[](fg:#3e68d7 bg:#ff966c)\
$git_branch\
[ ](fg:#ff966c)\
"""
# $git_status\

# Disable the blank line at the start of the prompt
# add_newline = false
[hostname]
style = "bg:#41a6b5"
ssh_only = true
ssh_symbol = '󰴽'
format= '[$hostname $ssh_symbol ]($style)'

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#41a6b5 fg:#c8d3f5"
style_root = "bg:#c53b53 fg:#c8d3f5"
format = '[ 󰯙 $user ]($style)'

[directory]
style = "bg:#3e68d7"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#ff966c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#ff966c"
format = '[$all_status$ahead_behind ]($style)'

