
format = """
[](fg:#2ecc71)\
[ ](fg:white bg:#2ecc71)\
$hostname\
$username\
[](fg:#2ecc71 bg:#3498db )\
$directory\
[](fg:#3498db bg:#f1c40f)\
$git_branch\
$git_status\
[](fg:#f1c40f bg:#1abc9c)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[ ](fg:#1abc9c)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false
[hostname]
style = "bg:#2ecc71"
ssh_only = true
ssh_symbol = '󰴽'
format= '[$hostname $ssh_symbol ]($style)'

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#2ecc71"
style_root = "bg:#6c71c4"
format = '[$user ]($style)'

[directory]
style = "bg:#3498db"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#f1c40f"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#f1c40f"
format = '[$all_status$ahead_behind ]($style)'


[c]
symbol = " "
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#1abc9c"
format = '[ $symbol ($version) ]($style)'
