---
gui:
  showBottomLine: false
  showRandomTip: false
  nerdFontsVersion: '3'

disableStartupPopups: true
customCommands:
  - key: '<c-d>'
    context: 'files'
    command: 'git difftool {{.SelectedFile.Name}}'

