lastupdatecheck: 0
recentrepos:
- /mnt/ssd1/home/reid/Repositories/dotfiles
- /mnt/ssd1/home/reid/Repositories/Shipwright
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: false
ignorewhitespaceindiffview: false
